### ISSUE TITLE
Possible connection leak

### ISSUE THREAD

**Issue by chrsan** [expectedsh/go-sonic#15]
In `driver.go`:

```go
func (c *driver) Quit() error {
	err := c.write("QUIT")
	if err != nil {
		return err
	}

	// should get ENDED
	_, err = c.read()
	c.close()
	return err
}
```
If `c.write` returns an error and the underlying TCP connection isn't closed, `c.close()` will never be called and the connection will be leaked since there's no way of closing the connection as a consumer since that method isn't exported.

**Comment by alexisvisco** [comment]
Thanks you for your report. 

I will fix this soon.
