### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by finnsson** [expectedsh/go-sonic#21]
Hi,

I cannot find the license for the package. Would you mind adding a license (eg MIT, BSD-2, etc)?

You can find a guide here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Regards,
Finnsson

**Comment by remicaumette** [comment]
Hi @finnsson,
Thanks for your feedback, I've added the license.
