### ISSUE TITLE
How do you use sonic with mongodb?

### ISSUE THREAD

**Issue by shuwenhe** [expectedsh/go-sonic#6]
our production environment is mongodb, but I read the relevant documents provided by Sonic official, did not introduce how to use sonic combined with mongodb, can you provide more detailed documentation? How do you use sonic with mongodb?

**Comment by alexisvisco** [comment]
As I have send you some useful information by mail I am closing this issue.

**Comment by nithinkashyapn** [comment]
Can you share with me as well?
