### ISSUE TITLE
Bulk Push stuck in loop

### ISSUE THREAD

**Issue by BenSlabbert** [expectedsh/go-sonic#9]
Thank you for the library :)

Been playing around with it and got stuck trying the first example. I have set up a dummy repo here: https://github.com/BenSlabbert/go-sonic-test

When running sonic `docker-compose up` and then the project `go run main.go`

the program hangs.

after some debugging it looks like it gets stuck in `func splitText(longString string, maxLen int) []string` in the file `ingester.go`. Seeing as this is called by the `Push` func, that too is affected

**Comment by BenSlabbert** [comment]
Did some more digging and it looks like the process hangs when we make a call to read the response from sonic in `ingester.go` `func (i ingesterChannel) BulkPush(collection, bucket string, parallelRoutines int, records []IngestBulkRecord) (errs []IngestBulkError)`

```
_, err = conn.read()
```

from the sonic logs:
```
sonic_1  | (INFO) - starting up
sonic_1  | (INFO) - started
sonic_1  | (INFO) - tasker is now active
sonic_1  | (INFO) - listening on tcp://0.0.0.0:1491
sonic_1  | (INFO) - kv store not in pool for collection: movies <50dbb12c>, opening it
sonic_1  | (INFO) - fst store not in pool for collection: movies <50dbb12c> / bucket: general <b742bdec>, opening it
sonic_1  | (INFO) - must initialize push executor oid-to-iid and iid-to-oid
sonic_1  | (INFO) - got push executor stored iid-to-terms: {}
sonic_1  | (INFO) - has push executor term-to-iids: 0
sonic_1  | (INFO) - graph consolidation scheduled on pool key: <50dbb12c>/<b742bdec>
sonic_1  | (INFO) - has push executor term-to-iids: 0
sonic_1  | (INFO) - has push executor iid-to-terms commits: [204664878, 1695192752]
sonic_1  | (INFO) - took 16ms/16890us/16890190ns to process channel message
```

**Comment by alexisvisco** [comment]
I will dive into your error after my work, that's strange this function was added by @StevenACoffman. 
This is an abnormal error and this should be fixed.

**Comment by BenSlabbert** [comment]
ok I think the issue is here:

https://github.com/expectedsh/go-sonic/blob/master/sonic/ingester.go from lines 174-183

```
				err := i.Push(collection, bucket, rec.Object, rec.Text)
				if err != nil {
					addBulkError(&errs, rec, err, errMutex)
					continue
				}
				// sonic should sent OK
				_, err = conn.read()
				if err != nil {
					addBulkError(&errs, rec, err, errMutex)
				}
```

on line 180 we try to read from the connection

```
_, err = conn.read()
```

However we already get the `OK` response from sonic when we call `err := i.Push(collection, bucket, rec.Object, rec.Text)` on line 174

**Comment by BenSlabbert** [comment]
I created a PR here, I tested the change and it seems to solve the issue: https://github.com/expectedsh/go-sonic/pull/10

**Comment by alexisvisco** [comment]
The sonic library is single threaded, to dispatch works this is the job of the `Bulk` functions.
What do you mean exactly by `Note, this only works with a single go routine, using more than 1 causes problems` ?

**Comment by BenSlabbert** [comment]
When invoking 

```
BulkPush(collection, bucket string, parallelRoutines int, records []IngestBulkRecord) []IngestBulkError
```

Using only 1 go routine in this func works, when using more than 1 the application hangs.

Note, this is not always the case, sometimes it works and sometimes not, I believe it is how we set up the various go routines here:

https://github.com/expectedsh/go-sonic/blob/1e8fa5e042c3cbf2849f2ddf99651efadd1c7cce/sonic/ingester.go#L217

and here:

https://github.com/expectedsh/go-sonic/blob/1e8fa5e042c3cbf2849f2ddf99651efadd1c7cce/sonic/ingester.go#L167

**Comment by alexisvisco** [comment]
Hum, that's strange this is not the expected result because the main goal of this function is to dispatch the records among multiple goroutines to reduce times of ingesting/pop/search/count... 

This is for that reason that I implement a "pool" of connection. 

I will open an issue about that, thanks for reporting. I will be doing some refactors of the code after merging your PR.

**Comment by BenSlabbert** [comment]
pr here: https://github.com/expectedsh/go-sonic/pull/13
